Watching for file changes with StatReloader
"GET / HTTP/1.1" 302 0
"GET /login/?next=/ HTTP/1.1" 200 4160
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 4674
"POST /login/?next=/ HTTP/1.1" 200 4160
"GET /register/ HTTP/1.1" 200 6864
"POST /register/ HTTP/1.1" 200 7554
"POST /register/ HTTP/1.1" 200 7372
"POST /register/ HTTP/1.1" 302 0
"GET /login/ HTTP/1.1" 200 4611
"POST /login/ HTTP/1.1" 302 0
Internal Server Error: /
Traceback (most recent call last):
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\shift_ai2\shift_ai\accounts\views.py", line 34, in dashboard
    month_end = today.replace(month=today.month + 1, day=1) - timedelta(days=1)
NameError: name 'timedelta' is not defined
"GET / HTTP/1.1" 500 76263
C:\shift_ai2\shift_ai\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\shift_ai2\shift_ai\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\shift_ai2\shift_ai\accounts\views.py", line 57, in dashboard
    return render(request, 'accounts/dashboard.html', context)
  File "C:\shift_ai2\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 489, in parse
    raise self.error(token, e)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 705, in __init__
    filter_func = parser.find_filter(filter_name)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 615, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'div'
"GET / HTTP/1.1" 500 240491
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 4674
Internal Server Error: /
Traceback (most recent call last):
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\shift_ai2\shift_ai\accounts\views.py", line 57, in dashboard
    return render(request, 'accounts/dashboard.html', context)
  File "C:\shift_ai2\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 489, in parse
    raise self.error(token, e)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 705, in __init__
    filter_func = parser.find_filter(filter_name)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 615, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'div'
"GET / HTTP/1.1" 500 240491
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 4674
"GET /login/ HTTP/1.1" 200 4160
"POST /login/ HTTP/1.1" 302 0
Internal Server Error: /
Traceback (most recent call last):
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\shift_ai2\shift_ai\accounts\views.py", line 57, in dashboard
    return render(request, 'accounts/dashboard.html', context)
  File "C:\shift_ai2\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 489, in parse
    raise self.error(token, e)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 705, in __init__
    filter_func = parser.find_filter(filter_name)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 615, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'div'
"GET / HTTP/1.1" 500 240363
C:\shift_ai2\shift_ai\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\shift_ai2\shift_ai\eval\views.py changed, reloading.
Watching for file changes with StatReloader
C:\shift_ai2\shift_ai\eval\views.py changed, reloading.
Watching for file changes with StatReloader
C:\shift_ai2\shift_ai\shift\views.py changed, reloading.
Watching for file changes with StatReloader
C:\shift_ai2\shift_ai\shift\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\shift_ai2\shift_ai\accounts\views.py", line 61, in dashboard
    return render(request, 'accounts/dashboard.html', context)
  File "C:\shift_ai2\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\shift_ai2\venv\lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'dashboard' not found. 'dashboard' is not a valid view function or pattern name.
"GET / HTTP/1.1" 500 177823
Internal Server Error: /
Traceback (most recent call last):
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\shift_ai2\shift_ai\accounts\views.py", line 61, in dashboard
    return render(request, 'accounts/dashboard.html', context)
  File "C:\shift_ai2\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\shift_ai2\venv\lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'dashboard' not found. 'dashboard' is not a valid view function or pattern name.
"GET / HTTP/1.1" 500 177823
"GET / HTTP/1.1" 200 10338
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 4674
"GET /store-settings/ HTTP/1.1" 200 9597
"GET /staff-management/ HTTP/1.1" 200 8385
Internal Server Error: /shift/
Traceback (most recent call last):
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\shift_ai2\shift_ai\shift\views.py", line 56, in shift_creation
    return render(request, 'shift/shift_creation.html', context)
  File "C:\shift_ai2\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\shift_ai2\venv\lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'generate_ai_shifts' not found. 'generate_ai_shifts' is not a valid view function or pattern name.
"GET /shift/ HTTP/1.1" 500 175320
Internal Server Error: /shift/
Traceback (most recent call last):
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\shift_ai2\shift_ai\shift\views.py", line 56, in shift_creation
    return render(request, 'shift/shift_creation.html', context)
  File "C:\shift_ai2\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\shift_ai2\venv\lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'generate_ai_shifts' not found. 'generate_ai_shifts' is not a valid view function or pattern name.
"GET /shift/ HTTP/1.1" 500 175320
"GET /shift/staff-requests/ HTTP/1.1" 200 13517
Internal Server Error: /shift/staff-requests/
Traceback (most recent call last):
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\shift_ai2\shift_ai\shift\views.py", line 256, in staff_shift_requests
    return redirect('staff_shift_requests')
  File "C:\shift_ai2\venv\lib\site-packages\django\shortcuts.py", line 51, in redirect
    resolve_url(to, *args, **kwargs),
  File "C:\shift_ai2\venv\lib\site-packages\django\shortcuts.py", line 184, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'staff_shift_requests' not found. 'staff_shift_requests' is not a valid view function or pattern name.
"POST /shift/staff-requests/ HTTP/1.1" 500 98061
"GET /shift/staff-requests/ HTTP/1.1" 200 15566
"GET /shift/staff-view/ HTTP/1.1" 200 10391
"GET /eval/staff-evaluation/ HTTP/1.1" 200 8385
"GET /eval/attendance-records/ HTTP/1.1" 200 12800
"GET / HTTP/1.1" 200 10338
"GET /staff-management/ HTTP/1.1" 200 8385
"GET /staff-requirements/ HTTP/1.1" 200 12000
Internal Server Error: /shift/
Traceback (most recent call last):
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\shift_ai2\shift_ai\shift\views.py", line 56, in shift_creation
    return render(request, 'shift/shift_creation.html', context)
  File "C:\shift_ai2\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\shift_ai2\venv\lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'generate_ai_shifts' not found. 'generate_ai_shifts' is not a valid view function or pattern name.
"GET /shift/ HTTP/1.1" 500 175322
Internal Server Error: /shift/
Traceback (most recent call last):
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\shift_ai2\shift_ai\shift\views.py", line 56, in shift_creation
    return render(request, 'shift/shift_creation.html', context)
  File "C:\shift_ai2\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\shift_ai2\venv\lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'confirm_shifts' not found. 'confirm_shifts' is not a valid view function or pattern name.
"GET /shift/ HTTP/1.1" 500 175299
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 4674
Internal Server Error: /shift/
Traceback (most recent call last):
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\shift_ai2\shift_ai\shift\views.py", line 56, in shift_creation
    return render(request, 'shift/shift_creation.html', context)
  File "C:\shift_ai2\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\shift_ai2\venv\lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'confirm_shifts' not found. 'confirm_shifts' is not a valid view function or pattern name.
"GET /shift/ HTTP/1.1" 500 175299
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 4674
"GET / HTTP/1.1" 200 10338
Internal Server Error: /shift/
Traceback (most recent call last):
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\shift_ai2\shift_ai\shift\views.py", line 56, in shift_creation
    return render(request, 'shift/shift_creation.html', context)
  File "C:\shift_ai2\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\shift_ai2\venv\lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'confirm_shifts' not found. 'confirm_shifts' is not a valid view function or pattern name.
"GET /shift/ HTTP/1.1" 500 175015
Internal Server Error: /shift/
Traceback (most recent call last):
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\shift_ai2\shift_ai\shift\views.py", line 56, in shift_creation
    return render(request, 'shift/shift_creation.html', context)
  File "C:\shift_ai2\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\shift_ai2\venv\lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'confirm_shifts' not found. 'confirm_shifts' is not a valid view function or pattern name.
"GET /shift/ HTTP/1.1" 500 175015
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 10338
Internal Server Error: /shift/
Traceback (most recent call last):
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\shift_ai2\shift_ai\shift\views.py", line 56, in shift_creation
    return render(request, 'shift/shift_creation.html', context)
  File "C:\shift_ai2\venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\shift_ai2\venv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\shift_ai2\venv\lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\shift_ai2\venv\lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'confirm_shifts' not found. 'confirm_shifts' is not a valid view function or pattern name.
"GET /shift/ HTTP/1.1" 500 175015
"GET /shift/ HTTP/1.1" 200 11553
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 4674
"GET /eval/evaluation-input/ HTTP/1.1" 200 15305
"GET /shift/staff-requests/ HTTP/1.1" 200 15067
"GET /shift/staff-view/ HTTP/1.1" 200 10391
"GET /eval/staff-evaluation/ HTTP/1.1" 200 8385
"GET /eval/attendance-records/ HTTP/1.1" 200 12800
"GET /store-settings/ HTTP/1.1" 200 9597
"GET /staff-management/ HTTP/1.1" 200 8385
"GET /shift/ HTTP/1.1" 200 11553
Watching for file changes with StatReloader
<<<<<<< HEAD
"GET / HTTP/1.1" 200 10338
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 4674
"GET /eval/evaluation-input/ HTTP/1.1" 200 15305
"GET /shift/ HTTP/1.1" 200 11553
"GET /staff-requirements/ HTTP/1.1" 200 12000
"GET /eval/evaluation-input/ HTTP/1.1" 200 15305
Internal Server Error: /eval/evaluation-input/
Traceback (most recent call last):
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\shift_ai2\shift_ai\eval\views.py", line 49, in evaluation_input
    return redirect('evaluation_input')
  File "C:\shift_ai2\venv\lib\site-packages\django\shortcuts.py", line 51, in redirect
    resolve_url(to, *args, **kwargs),
  File "C:\shift_ai2\venv\lib\site-packages\django\shortcuts.py", line 184, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'evaluation_input' not found. 'evaluation_input' is not a valid view function or pattern name.
"POST /eval/evaluation-input/ HTTP/1.1" 500 97775
Watching for file changes with StatReloader
Not Found: /eval/
"GET /eval/ HTTP/1.1" 404 6239
"GET / HTTP/1.1" 200 10846
"GET /staff-management/ HTTP/1.1" 200 8385
"GET /store-settings/ HTTP/1.1" 200 9597
"GET / HTTP/1.1" 200 10338
"GET /staff-management/ HTTP/1.1" 200 8385
"GET /staff/1/ HTTP/1.1" 200 10770
"GET /shift/staff-requests/ HTTP/1.1" 200 15067
"GET /eval/evaluation-input/ HTTP/1.1" 200 17164
"GET /eval/attendance-records/ HTTP/1.1" 200 12800
"GET /store-settings/ HTTP/1.1" 200 9597
"GET /store-settings/ HTTP/1.1" 200 9597
"GET /staff-management/ HTTP/1.1" 200 8385
"GET /staff-requirements/ HTTP/1.1" 200 12000
Internal Server Error: /staff-requirements/
Traceback (most recent call last):
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\shift_ai2\shift_ai\accounts\views.py", line 163, in staff_requirements
    return redirect('staff_requirements')
  File "C:\shift_ai2\venv\lib\site-packages\django\shortcuts.py", line 51, in redirect
    resolve_url(to, *args, **kwargs),
  File "C:\shift_ai2\venv\lib\site-packages\django\shortcuts.py", line 184, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'staff_requirements' not found. 'staff_requirements' is not a valid view function or pattern name.
"POST /staff-requirements/ HTTP/1.1" 500 96978
"GET /staff-requirements/ HTTP/1.1" 200 14626
"GET /eval/evaluation-input/ HTTP/1.1" 200 17164
"GET /shift/staff-view/ HTTP/1.1" 200 10391
"GET /shift/staff-requests/ HTTP/1.1" 200 15067
"GET /shift/ HTTP/1.1" 200 11553
Forbidden (CSRF token missing.): /shift/generate-ai/
"POST /shift/generate-ai/ HTTP/1.1" 403 2534
"GET /shift/?start_date=2025-10-06&end_date=2025-11-05 HTTP/1.1" 200 11553
"GET /shift/?start_date=2025-10-01&end_date=2025-11-05 HTTP/1.1" 200 11553
"GET /shift/staff-view/ HTTP/1.1" 200 10391
"GET /eval/evaluation-input/ HTTP/1.1" 200 17164
"GET /eval/attendance-records/ HTTP/1.1" 200 12800
"GET /eval/staff-evaluation/ HTTP/1.1" 200 14037
=======
"GET / HTTP/1.1" 302 0
"GET /login/?next=/ HTTP/1.1" 200 4160
"GET / HTTP/1.1" 302 0
"GET /login/?next=/ HTTP/1.1" 200 4160
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 4674
"POST /login/?next=/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET /login/ HTTP/1.1" 200 4579
"POST /login/ HTTP/1.1" 200 4160
"POST /login/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET /login/ HTTP/1.1" 200 4579
"POST /login/ HTTP/1.1" 200 4160
"GET /register/ HTTP/1.1" 200 6864
- Broken pipe from ('127.0.0.1', 59065)
Internal Server Error: /register/
Traceback (most recent call last):
  File "C:\Users\minec\Documents\23a31g0001\sistemkaihatu\Shift_ai2\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\minec\Documents\23a31g0001\sistemkaihatu\Shift_ai2\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: auth_user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\minec\Documents\23a31g0001\sistemkaihatu\Shift_ai2\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\minec\Documents\23a31g0001\sistemkaihatu\Shift_ai2\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\minec\Documents\23a31g0001\sistemkaihatu\Shift_ai2\shift_ai\accounts\views.py", line 200, in register
    user = form.save()
  File "C:\Users\minec\Documents\23a31g0001\sistemkaihatu\Shift_ai2\shift_ai\accounts\forms.py", line 82, in save
    user.save()
    ~~~~~~~~~^^
  File "C:\Users\minec\Documents\23a31g0001\sistemkaihatu\Shift_ai2\venv\Lib\site-packages\django\contrib\auth\base_user.py", line 65, in save
    super().save(*args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\minec\Documents\23a31g0001\sistemkaihatu\Shift_ai2\venv\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\minec\Documents\23a31g0001\sistemkaihatu\Shift_ai2\venv\Lib\site-packages\django\db\models\base.py", line 1008, in save_base
    updated = self._save_table(
        raw,
    ...<4 lines>...
        update_fields,
    )
  File "C:\Users\minec\Documents\23a31g0001\sistemkaihatu\Shift_ai2\venv\Lib\site-packages\django\db\models\base.py", line 1169, in _save_table
    results = self._do_insert(
        cls._base_manager, using, fields, returning_fields, raw
    )
  File "C:\Users\minec\Documents\23a31g0001\sistemkaihatu\Shift_ai2\venv\Lib\site-packages\django\db\models\base.py", line 1210, in _do_insert
    return manager._insert(
           ~~~~~~~~~~~~~~~^
        [self],
        ^^^^^^^
    ...<3 lines>...
        raw=raw,
        ^^^^^^^^
    )
    ^
  File "C:\Users\minec\Documents\23a31g0001\sistemkaihatu\Shift_ai2\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\minec\Documents\23a31g0001\sistemkaihatu\Shift_ai2\venv\Lib\site-packages\django\db\models\query.py", line 1868, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\minec\Documents\23a31g0001\sistemkaihatu\Shift_ai2\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\minec\Documents\23a31g0001\sistemkaihatu\Shift_ai2\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\minec\Documents\23a31g0001\sistemkaihatu\Shift_ai2\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\minec\Documents\23a31g0001\sistemkaihatu\Shift_ai2\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\minec\Documents\23a31g0001\sistemkaihatu\Shift_ai2\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\minec\Documents\23a31g0001\sistemkaihatu\Shift_ai2\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\minec\Documents\23a31g0001\sistemkaihatu\Shift_ai2\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\minec\Documents\23a31g0001\sistemkaihatu\Shift_ai2\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: auth_user.username
"POST /register/ HTTP/1.1" 500 166694
Forbidden (CSRF token from POST incorrect.): /login/
"POST /login/?next=/ HTTP/1.1" 403 2546
Forbidden (CSRF token from POST incorrect.): /login/
"POST /login/?next=/ HTTP/1.1" 403 2546
"GET /login/?next=/ HTTP/1.1" 200 4160
"GET /login/?next=/ HTTP/1.1" 200 4160
"GET /login/?next=/ HTTP/1.1" 200 4160
"GET /login/?next=/ HTTP/1.1" 200 4160
"GET /login/?next=/ HTTP/1.1" 200 4160
"GET / HTTP/1.1" 302 0
"GET /login/ HTTP/1.1" 200 4579
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 4674
"POST /login/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET /login/ HTTP/1.1" 200 4579
Watching for file changes with StatReloader
"GET /login/ HTTP/1.1" 200 4160
Not Found: /.well-known/appspecific/com.chrome.devtools.json
"GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 4785
"POST /login/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 10327
Not Found: /.well-known/appspecific/com.chrome.devtools.json
"GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 4785
Method Not Allowed (GET): /logout/
"GET /logout/ HTTP/1.1" 405 0
Not Found: /.well-known/appspecific/com.chrome.devtools.json
"GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 4785
Not Found: /.well-known/appspecific/com.chrome.devtools.json
"GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 4785
"GET / HTTP/1.1" 200 10327
Not Found: /.well-known/appspecific/com.chrome.devtools.json
"GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 4785
"GET / HTTP/1.1" 200 10327
Not Found: /.well-known/appspecific/com.chrome.devtools.json
"GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 4785
"GET /store-settings/ HTTP/1.1" 200 9586
Not Found: /.well-known/appspecific/com.chrome.devtools.json
"GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 4785
"GET /staff-management/ HTTP/1.1" 200 8343
Not Found: /.well-known/appspecific/com.chrome.devtools.json
"GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 4785
"GET /staff-requirements/ HTTP/1.1" 200 11989
Not Found: /.well-known/appspecific/com.chrome.devtools.json
"GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 4785
"GET /shift/ HTTP/1.1" 200 11542
Not Found: /.well-known/appspecific/com.chrome.devtools.json
"GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 4785
"GET /staff-requirements/ HTTP/1.1" 200 11989
Not Found: /.well-known/appspecific/com.chrome.devtools.json
"GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 4785
"GET /staff-management/ HTTP/1.1" 200 8343
Not Found: /.well-known/appspecific/com.chrome.devtools.json
"GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 4785
"GET /shift/ HTTP/1.1" 200 11542
Not Found: /.well-known/appspecific/com.chrome.devtools.json
"GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 4785
"GET /eval/evaluation-input/ HTTP/1.1" 200 15283
Not Found: /.well-known/appspecific/com.chrome.devtools.json
"GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 4785
"GET /eval/evaluation-input/ HTTP/1.1" 200 15283
Not Found: /.well-known/appspecific/com.chrome.devtools.json
"GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 4785
"GET /shift/staff-requests/ HTTP/1.1" 200 13506
Not Found: /.well-known/appspecific/com.chrome.devtools.json
"GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 4785
"GET /shift/staff-view/ HTTP/1.1" 200 10349
Not Found: /.well-known/appspecific/com.chrome.devtools.json
"GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 4785
"GET /eval/staff-evaluation/ HTTP/1.1" 200 8343
Not Found: /.well-known/appspecific/com.chrome.devtools.json
"GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 4785
"GET /eval/attendance-records/ HTTP/1.1" 200 12758
Not Found: /.well-known/appspecific/com.chrome.devtools.json
"GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 4785
"GET /shift/staff-requests/ HTTP/1.1" 200 13506
Not Found: /.well-known/appspecific/com.chrome.devtools.json
"GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 4785
"GET /eval/attendance-records/ HTTP/1.1" 200 12758
Not Found: /.well-known/appspecific/com.chrome.devtools.json
"GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 4785
"GET /eval/staff-evaluation/ HTTP/1.1" 200 8343
Not Found: /.well-known/appspecific/com.chrome.devtools.json
"GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 4785
"GET / HTTP/1.1" 200 10327
Not Found: /.well-known/appspecific/com.chrome.devtools.json
"GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 4785
"GET /store-settings/ HTTP/1.1" 200 9586
Not Found: /.well-known/appspecific/com.chrome.devtools.json
"GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 4785
"GET /staff-requirements/ HTTP/1.1" 200 11989
Not Found: /.well-known/appspecific/com.chrome.devtools.json
"GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 4785
"GET /staff-management/ HTTP/1.1" 200 8343
Not Found: /.well-known/appspecific/com.chrome.devtools.json
"GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 4785
"GET /shift/ HTTP/1.1" 200 11542
Not Found: /.well-known/appspecific/com.chrome.devtools.json
"GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 4785
"GET /eval/evaluation-input/ HTTP/1.1" 200 15283
Not Found: /.well-known/appspecific/com.chrome.devtools.json
"GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 4785
"GET /shift/staff-requests/ HTTP/1.1" 200 13506
Not Found: /.well-known/appspecific/com.chrome.devtools.json
"GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 4785
"GET /shift/staff-view/ HTTP/1.1" 200 10349
Not Found: /.well-known/appspecific/com.chrome.devtools.json
"GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 4785
"GET /eval/staff-evaluation/ HTTP/1.1" 200 8343
Not Found: /.well-known/appspecific/com.chrome.devtools.json
"GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 4785
"GET /shift/staff-requests/ HTTP/1.1" 200 13506
Not Found: /.well-known/appspecific/com.chrome.devtools.json
"GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 4785
"GET /eval/attendance-records/ HTTP/1.1" 200 12758
Not Found: /.well-known/appspecific/com.chrome.devtools.json
"GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 4785
"GET /shift/staff-requests/ HTTP/1.1" 200 13506
Not Found: /.well-known/appspecific/com.chrome.devtools.json
"GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 4785
C:\Users\minec\Documents\23a31g0001\sistemkaihatu\Shift_ai2\shift_ai\shift_ai\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\minec\Documents\23a31g0001\sistemkaihatu\Shift_ai2\shift_ai\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\minec\Documents\23a31g0001\sistemkaihatu\Shift_ai2\shift_ai\shift\admin_views.py changed, reloading.
Watching for file changes with StatReloader
>>>>>>> 363bada5127bd13efb91fb3e13fcc865464abc68
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\shift_ai2\shift_ai\accounts\views.py", line 20, in dashboard
    return redirect('admin:dashboard')
  File "C:\shift_ai2\venv\lib\site-packages\django\shortcuts.py", line 51, in redirect
    resolve_url(to, *args, **kwargs),
  File "C:\shift_ai2\venv\lib\site-packages\django\shortcuts.py", line 184, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'dashboard' not found. 'dashboard' is not a valid view function or pattern name.
"GET / HTTP/1.1" 500 94511
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 4099
Internal Server Error: /
Traceback (most recent call last):
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\shift_ai2\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\shift_ai2\shift_ai\accounts\views.py", line 20, in dashboard
    return redirect('admin:dashboard')
  File "C:\shift_ai2\venv\lib\site-packages\django\shortcuts.py", line 51, in redirect
    resolve_url(to, *args, **kwargs),
  File "C:\shift_ai2\venv\lib\site-packages\django\shortcuts.py", line 184, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\shift_ai2\venv\lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'dashboard' not found. 'dashboard' is not a valid view function or pattern name.
"GET / HTTP/1.1" 500 94776
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 4099
